name: 🚀 Deploy website on push

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  ssh-deploy:
    name: 🚀 SSH Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🔑 Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 📡 Deploy via SSH
      run: |
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
        git remote add server ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_PORT }}${{ secrets.SSH_DESTINATION_PATH }} || true
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} "cd ${{ secrets.SSH_DESTINATION_PATH }} && git clean -fd && git reset --hard HEAD"
        git push server HEAD:main --force